In [2]:
a=[1,2,3]
# a[:0]=10 이건 오류
a[:0]=[10]
#이렇게 해줘야 하는 이유가 슬라이싱한 결과는 리스트고, 그 리스트를
#대체하겠다는 의미라서, 숫자 10을 넣으면 안돼고 [10]과 같이 넣어주어야 함.
print a

[10, 1, 2, 3]


In [4]:
#중첩리스트는 시험문제 내기에 좋지롱
L = [1, ['a', ['x', 'y'], 'b'], 3]
print L[0]
print L[1]
print L[1][1]
print L[1][1][1]
#이거에 해당하는 원소 값을 쓰시오 뭐 이런식으로 문제내기 짱 좋닿ㅎㅎㅎㅎㅎㅎ
#대문자 L의 원소의 갯수는 3개인 것임. 1 하고 ['a',['x','y'],'b'] 하고 3

1
['a', ['x', 'y'], 'b']
['x', 'y']
y


In [5]:
sun, mon, tue, wed, thu, fri, sat = range(7)
#range는 결과가 리스트임
#리스트의 각각의 원소가 모두 각각 sun mon 등에 할당되는 예제임
#그런데 파이썬에서 저렇게 콤마콤마 하는거는 튜플
#결과적으로 sun, mon, tue, wed, thu, fri, sat = range(7) 는
#(sun, mon, tue, wed, thu, fri, sat) = range(7)와 같은 코드임
print sun, mon, tue, wed, thu, fri, sat

0 1 2 3 4 5 6


In [7]:
#append는 활용도가 제일 높은 메소드. 리스트의 마지막에 새로운거 삽입.
#s.insert(3,4)에서는 3은 인덱스, 4가 넣어줄 값임.
#s.index(3)은 3이라는 값의 인덱스를 반환해주는것임
#같은원소 여러개 있으면 앞에거의 인덱스가 나옴.
#저 안에 없는 원소가 들어가면 오류뜸

In [8]:
#s.reverse(),s.sort() 리스트 자체에서 부르는 메소드 reverse는 리스트 자체를 변경
#그러나 내장함수 reverse와 내장함수 sort는 기존의 리스트를 변경하지 않고 새로운
#리스트를 반환하여줌
s=[1,2,-10,-7,100]
s.sort()
print s
print s.sort()
#s.sort()는 반환값이없다 혹은 None을 반환한다.

[-10, -7, 1, 2, 100]
None


In [9]:
#extend와 append의 차이 알아두기
#extend에 원소로 튜플이랑 리스트 둘 다 들어가도 상관 없음, 어차피 중요한게
#자료의 변경 불가능이 아니라 여러 자료를 가지고 있다는 것이니까
s.extend?
#예전에 했던 함수 설명 쓰는 그 예제 참고하자.

In [10]:
L=[1,5,3,9,8,4,2]
L.sort()#머지소트의 변형 팀소트.....
#어떤 소트 방식이라도 cmp는 어딘가에서 사용
#버블정렬은 양옆을 계속 비교해가는거......
print L

[1, 2, 3, 4, 5, 8, 9]


In [12]:
def mycmp(a1, a2):#이렇게 넣어줄 것을 만들때는 규칙을 잘 정해주어야 함.
    return cmp(a2, a1)

L = [1, 5, 3, 2, 4, 6]
L.sort(mycmp)#함수의 인자로 함수를 줌.
#그냥 받아들이면 됨 함수를 인자로 넣어줄 수 있다ㅎㅎㅎㅎㅎㅎ
print type(mycmp)
print L

<type 'function'>
[6, 5, 4, 3, 2, 1]


In [14]:
def cmp_1(a1, a2):
    return cmp(a1[1], a2[1])
def cmp_2(a1, a2):
    return cmp(a1[2], a2[2])
L = [ ('lee', 5, 38), ('kim', 3, 28), ('jung', 10, 36)]

L.sort()
print 'sorted by name:', L

L.sort(cmp_1)
print 'sorted by experience:', L

L.sort(cmp_2)
print 'sorted by age:', L

L=[1,6,3,8,6,2,9]#임의로 정수가 들어간 리스트 L
L.sort(reverse=True)
#reverse 인자의 기본적 디폴트가 false -> 오름차순으로 정렬
print L

L.sort?
"""
Docstring:
L.sort(cmp=None, key=None, reverse=False) -- stable sort *IN PLACE*;
cmp(x, y) -> -1, 0, 1
Type:      builtin_function_or_method
"""
#아무것도 안주면 cmp는 None, key에는 None, reverse에는 False가 디폴트로 들어감.
#첫번째 인자는 cmp=mycmp와 같이 써줄 필요 없음.
#그러나 key, reverse에 무엇인가를 넣으려면 반드시 그것을 명시해주어야함
#key에 int를 주면 int내장함수 한 결과가 cmp에 들어가게 됨


sorted by name: [('jung', 10, 36), ('kim', 3, 28), ('lee', 5, 38)]
sorted by experience: [('kim', 3, 28), ('lee', 5, 38), ('jung', 10, 36)]
sorted by age: [('kim', 3, 28), ('jung', 10, 36), ('lee', 5, 38)]
[9, 8, 6, 6, 3, 2, 1]


In [15]:
L=[k*k for k in range(10)]
#대괄호가 열리자마자 가장먼저 있는게 식임...
#x하나만 있더라도 식이 됨
print L
#집합의 표기방법과 함께 보면 좋음.

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


##중간고사에서는 리스트 내포 리터럴을 일반식으로, 일반식을 리스트 내포 리터럴로 바꿀 수 있어야 함.

In [18]:
[(x,y,z)for x in range(1,30) for y in range(x,30) for z in range(y,30)\
 if x**2 + y**2 ==z**2]
#y는 x와 같거나 크고 z는 y보다 같거나 크다
#여기서 range를 3000으로 주면 정말 오래 걸리게 됨.

[(3, 4, 5),
 (5, 12, 13),
 (6, 8, 10),
 (7, 24, 25),
 (8, 15, 17),
 (9, 12, 15),
 (10, 24, 26),
 (12, 16, 20),
 (15, 20, 25),
 (20, 21, 29)]

In [20]:
[(x,y,z)for x in range(1,30) for y in range(x,30) for z in range(y,30)]
#이렇게 if문을 뺄 경우 엄청나게 길게 출력됨......!!!!!!


[(1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 1, 4),
 (1, 1, 5),
 (1, 1, 6),
 (1, 1, 7),
 (1, 1, 8),
 (1, 1, 9),
 (1, 1, 10),
 (1, 1, 11),
 (1, 1, 12),
 (1, 1, 13),
 (1, 1, 14),
 (1, 1, 15),
 (1, 1, 16),
 (1, 1, 17),
 (1, 1, 18),
 (1, 1, 19),
 (1, 1, 20),
 (1, 1, 21),
 (1, 1, 22),
 (1, 1, 23),
 (1, 1, 24),
 (1, 1, 25),
 (1, 1, 26),
 (1, 1, 27),
 (1, 1, 28),
 (1, 1, 29),
 (1, 2, 2),
 (1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 2, 6),
 (1, 2, 7),
 (1, 2, 8),
 (1, 2, 9),
 (1, 2, 10),
 (1, 2, 11),
 (1, 2, 12),
 (1, 2, 13),
 (1, 2, 14),
 (1, 2, 15),
 (1, 2, 16),
 (1, 2, 17),
 (1, 2, 18),
 (1, 2, 19),
 (1, 2, 20),
 (1, 2, 21),
 (1, 2, 22),
 (1, 2, 23),
 (1, 2, 24),
 (1, 2, 25),
 (1, 2, 26),
 (1, 2, 27),
 (1, 2, 28),
 (1, 2, 29),
 (1, 3, 3),
 (1, 3, 4),
 (1, 3, 5),
 (1, 3, 6),
 (1, 3, 7),
 (1, 3, 8),
 (1, 3, 9),
 (1, 3, 10),
 (1, 3, 11),
 (1, 3, 12),
 (1, 3, 13),
 (1, 3, 14),
 (1, 3, 15),
 (1, 3, 16),
 (1, 3, 17),
 (1, 3, 18),
 (1, 3, 19),
 (1, 3, 20),
 (1, 3, 21),
 (1, 3, 22),
 (1, 3, 23),
 (1, 3, 24

In [21]:
list_a = ['A', 'B']
list_b = ['C', 'D']
print [x+y for x in list_a for y in list_b]
#이거는 x랑 y에 상관관계가 없기 때문에 두 반복문을 바꿔써도 상관 없음.
print
print [[x+y for x in list_a] for y in list_b]
#리스트 내포가 중첩되어있는 형태.
#이건 먼저 y에 C를 대입을 해 놓고 그 다음에 안에 있는 반복을 돌려주게 되는 것임.
#바깥 리스트 내포의 원소는 2개.(바깥의 변수는 y인데, y는 c와 d 2개 이므로)
#리스트 안에는 리스트 원소가 있는것임.

['AC', 'AD', 'BC', 'BD']

[['AC', 'BC'], ['AD', 'BD']]


In [22]:
#print [[x+y for x in list_a] for y in list_b]와 동일한 리스트 내포가 아닌코드
l = []
for y in list_b:
    l2 = []#새로운 리스트의 생성
    for x in list_a:
        l2.append(x+y)
    l.append(l2)#지금 막 구성이 끝난 l2를 집어넣음. 실제로 l2는 총2번 추가됨.
print l

[['AC', 'BC'], ['AD', 'BD']]


In [23]:
a = [1, 2, 3, 4, 5]
b = range(10)
print a
print a[0]
print b
print b[1]
#콘솔에 가져갈때는 %paste하면 다 들어가짐
#파이썬에는 배열이 없음->리스트를 배열처럼 사용해야함....

[1, 2, 3, 4, 5]
1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1


In [24]:
#0으로 초기화 된 사이즈 10인 1차원 배열의 생성
a = [0] * 10
a

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [25]:
#2차원 배열처럼 활용하기
mat = [     [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]     ]
print mat
print mat[1][2]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
6


In [27]:
#numppy모듈을 쓰면 이 안에는 array라는 게 있어서 실제로 행렬의 생성이 가능함
from numpy import *


#장점 1.여러 배열을 손쉽게 만들 수 있음
a = array(((1,2,3), (4,5,6), (7, 8, 9))) # 3*3 행렬 생성
print a
print

b = zeros((3,3))#0으로 초기화 된 배열이 나옴
print b
print

c = ones((3,3))#1로 초기화 된 배열이 나옴
print c
print


#장점 2. 배열 자체에 산술 연산을 효과적으로 처리 가능
f = a + c     # 각 원소들끼리의 덧셈
print f
print

d = a * a     # 각 원소들끼리의 곱셈
print d
print

e = dot(a, c) # 일반적인 행렬 곱셈 
print e
print

#장점 3 선형대수에 관한 각종 수학적 연산을 효과적으로 지원
from numpy.linalg import *
g = inv(a)#역행렬을 바로 구할수 있음
print g
print

h = eig(a)#고유벡터 eigen vetor
print h
print

#셤은 안나옴

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[  2.   3.   4.]
 [  5.   6.   7.]
 [  8.   9.  10.]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

[[  6.   6.   6.]
 [ 15.  15.  15.]
 [ 24.  24.  24.]]

[[ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]
 [  9.00719925e+15  -1.80143985e+16   9.00719925e+15]
 [ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]]

(array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))



In [30]:
dir()#내가 쓸 수 있는 모든 이름들을 출력해줌
print __name__ #이 환경의 이름이 __main__이다
#__가 달린거는 다 특별한 것임
print __doc__#ipython환경의 상호작용을 위해 자동으로 만들어진 모듈


__main__
Automatically created module for IPython interactive environment


In [35]:
import math#이 모듈에도 __name__과 __doc__이 있음
print math.__name__#이 모듈의 이름
print math.__doc__#이 모듈의 설명 __doc__ : 문서문자열
math?
#위에 결과랑 내용이 같음 함수이름쓰면 함수설명나오는데 지금처럼 모듈이름쓰면 모듈설명
#이건 매우 중요한 내용임

math
This module is always available.  It provides access to the
mathematical functions defined by the C standard.


###명령행 인수

In [ ]:
"""
자바에서......
public static void main(String[] arg){

}
int main(int argc,char**argv){

}
hwp를 치면 hwp.exe라는게 어딘가에는 있음
hwp aaa bbb ccc ddd fff eee (hwp뒤에있는게 명령행 인자)이런식으로 쳐주게 되면
argc에는 hwp포함해서 총 5개가들어감(count)
argv에는 뒤에 명령행 인자들의 이름이 들어감...

java Hwp datshda fkjdsew asdo


python arg.py
ipython arg.py
cmd에서 이렇게 치면 실행됨.

명령행 인자를 가져오는 건 기본 파이썬에는 없고 모듈을 가져와야 함.

# file: arg.py
import sys
print sys.argv
이렇게 쓰면 파일명 포함한 인자들을 출력해줌.

c드라이브 사용자 유진 폴더에 메모 확인

첫번째 인자 찍으려면 
인덱스 0이 아니고 1부터 줘야함(0에는 파일명 들어가니까)

"""